/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as ApiLessonVideoRouteImport } from './routes/api/lesson/video'
import { Route as ApiCourseProgressRouteImport } from './routes/api/course/progress'
import { Route as ApiCourseDetailsRouteImport } from './routes/api/course/details'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ModulesModuleSlugLessonsLessonSlugRouteImport } from './routes/modules.$moduleSlug.lessons.$lessonSlug'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLessonVideoRoute = ApiLessonVideoRouteImport.update({
  id: '/api/lesson/video',
  path: '/api/lesson/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseProgressRoute = ApiCourseProgressRouteImport.update({
  id: '/api/course/progress',
  path: '/api/course/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseDetailsRoute = ApiCourseDetailsRouteImport.update({
  id: '/api/course/details',
  path: '/api/course/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleSlugLessonsLessonSlugRoute =
  ModulesModuleSlugLessonsLessonSlugRouteImport.update({
    id: '/modules/$moduleSlug/lessons/$lessonSlug',
    path: '/modules/$moduleSlug/lessons/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/course/details': typeof ApiCourseDetailsRoute
  '/api/course/progress': typeof ApiCourseProgressRoute
  '/api/lesson/video': typeof ApiLessonVideoRoute
  '/modules/$moduleSlug/lessons/$lessonSlug': typeof ModulesModuleSlugLessonsLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/course/details': typeof ApiCourseDetailsRoute
  '/api/course/progress': typeof ApiCourseProgressRoute
  '/api/lesson/video': typeof ApiLessonVideoRoute
  '/modules/$moduleSlug/lessons/$lessonSlug': typeof ModulesModuleSlugLessonsLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/course/details': typeof ApiCourseDetailsRoute
  '/api/course/progress': typeof ApiCourseProgressRoute
  '/api/lesson/video': typeof ApiLessonVideoRoute
  '/modules/$moduleSlug/lessons/$lessonSlug': typeof ModulesModuleSlugLessonsLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/course/details'
    | '/api/course/progress'
    | '/api/lesson/video'
    | '/modules/$moduleSlug/lessons/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/course/details'
    | '/api/course/progress'
    | '/api/lesson/video'
    | '/modules/$moduleSlug/lessons/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/course/details'
    | '/api/course/progress'
    | '/api/lesson/video'
    | '/modules/$moduleSlug/lessons/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCourseDetailsRoute: typeof ApiCourseDetailsRoute
  ApiCourseProgressRoute: typeof ApiCourseProgressRoute
  ApiLessonVideoRoute: typeof ApiLessonVideoRoute
  ModulesModuleSlugLessonsLessonSlugRoute: typeof ModulesModuleSlugLessonsLessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/video': {
      id: '/api/lesson/video'
      path: '/api/lesson/video'
      fullPath: '/api/lesson/video'
      preLoaderRoute: typeof ApiLessonVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course/progress': {
      id: '/api/course/progress'
      path: '/api/course/progress'
      fullPath: '/api/course/progress'
      preLoaderRoute: typeof ApiCourseProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course/details': {
      id: '/api/course/details'
      path: '/api/course/details'
      fullPath: '/api/course/details'
      preLoaderRoute: typeof ApiCourseDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleSlug/lessons/$lessonSlug': {
      id: '/modules/$moduleSlug/lessons/$lessonSlug'
      path: '/modules/$moduleSlug/lessons/$lessonSlug'
      fullPath: '/modules/$moduleSlug/lessons/$lessonSlug'
      preLoaderRoute: typeof ModulesModuleSlugLessonsLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  AuthLoginRoute: AuthLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCourseDetailsRoute: ApiCourseDetailsRoute,
  ApiCourseProgressRoute: ApiCourseProgressRoute,
  ApiLessonVideoRoute: ApiLessonVideoRoute,
  ModulesModuleSlugLessonsLessonSlugRoute:
    ModulesModuleSlugLessonsLessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
