/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin.index'
import { Route as ApiLessonVideoRouteImport } from './routes/api/lesson/video'
import { Route as ApiLessonMaterialRouteImport } from './routes/api/lesson/material'
import { Route as ApiCronBlobSweepRouteImport } from './routes/api/cron/blob-sweep'
import { Route as ApiCourseProgressRouteImport } from './routes/api/course/progress'
import { Route as ApiCourseDetailsRouteImport } from './routes/api/course/details'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUploadsRouteImport } from './routes/api/admin/uploads'
import { Route as ApiAdminCoursesRouteImport } from './routes/api/admin/courses'
import { Route as ApiLessonAiTestSaveResultsRouteImport } from './routes/api/lesson/ai-test/save-results'
import { Route as ApiLessonAiTestResultsRouteImport } from './routes/api/lesson/ai-test/results'
import { Route as ApiLessonAiTestGenerateRouteImport } from './routes/api/lesson/ai-test/generate'
import { Route as ApiLessonAiTestEvaluateRouteImport } from './routes/api/lesson/ai-test/evaluate'
import { Route as ApiAdminModulesModuleIdRouteImport } from './routes/api/admin/modules.$moduleId'
import { Route as ApiAdminCoursesCourseIdRouteImport } from './routes/api/admin/courses.$courseId'
import { Route as AuthedAdminCourseIdEditorRouteImport } from './routes/_authed/admin.$courseId.editor'
import { Route as ApiAdminModulesModuleIdLessonsRouteImport } from './routes/api/admin/modules.$moduleId.lessons'
import { Route as ApiAdminCoursesCourseIdModulesRouteImport } from './routes/api/admin/courses.$courseId.modules'
import { Route as ApiAdminCoursesCourseIdBoardRouteImport } from './routes/api/admin/courses.$courseId.board'
import { Route as AuthedModulesModuleSlugLessonsLessonSlugRouteImport } from './routes/_authed/modules.$moduleSlug.lessons.$lessonSlug'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const ApiLessonVideoRoute = ApiLessonVideoRouteImport.update({
  id: '/api/lesson/video',
  path: '/api/lesson/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonMaterialRoute = ApiLessonMaterialRouteImport.update({
  id: '/api/lesson/material',
  path: '/api/lesson/material',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBlobSweepRoute = ApiCronBlobSweepRouteImport.update({
  id: '/api/cron/blob-sweep',
  path: '/api/cron/blob-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseProgressRoute = ApiCourseProgressRouteImport.update({
  id: '/api/course/progress',
  path: '/api/course/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseDetailsRoute = ApiCourseDetailsRouteImport.update({
  id: '/api/course/details',
  path: '/api/course/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadsRoute = ApiAdminUploadsRouteImport.update({
  id: '/api/admin/uploads',
  path: '/api/admin/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCoursesRoute = ApiAdminCoursesRouteImport.update({
  id: '/api/admin/courses',
  path: '/api/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonAiTestSaveResultsRoute =
  ApiLessonAiTestSaveResultsRouteImport.update({
    id: '/api/lesson/ai-test/save-results',
    path: '/api/lesson/ai-test/save-results',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLessonAiTestResultsRoute = ApiLessonAiTestResultsRouteImport.update({
  id: '/api/lesson/ai-test/results',
  path: '/api/lesson/ai-test/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonAiTestGenerateRoute = ApiLessonAiTestGenerateRouteImport.update({
  id: '/api/lesson/ai-test/generate',
  path: '/api/lesson/ai-test/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonAiTestEvaluateRoute = ApiLessonAiTestEvaluateRouteImport.update({
  id: '/api/lesson/ai-test/evaluate',
  path: '/api/lesson/ai-test/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminModulesModuleIdRoute = ApiAdminModulesModuleIdRouteImport.update({
  id: '/api/admin/modules/$moduleId',
  path: '/api/admin/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCoursesCourseIdRoute = ApiAdminCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => ApiAdminCoursesRoute,
} as any)
const AuthedAdminCourseIdEditorRoute =
  AuthedAdminCourseIdEditorRouteImport.update({
    id: '/$courseId/editor',
    path: '/$courseId/editor',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const ApiAdminModulesModuleIdLessonsRoute =
  ApiAdminModulesModuleIdLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => ApiAdminModulesModuleIdRoute,
  } as any)
const ApiAdminCoursesCourseIdModulesRoute =
  ApiAdminCoursesCourseIdModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => ApiAdminCoursesCourseIdRoute,
  } as any)
const ApiAdminCoursesCourseIdBoardRoute =
  ApiAdminCoursesCourseIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => ApiAdminCoursesCourseIdRoute,
  } as any)
const AuthedModulesModuleSlugLessonsLessonSlugRoute =
  AuthedModulesModuleSlugLessonsLessonSlugRouteImport.update({
    id: '/modules/$moduleSlug/lessons/$lessonSlug',
    path: '/modules/$moduleSlug/lessons/$lessonSlug',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/app': typeof AuthedAppRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/admin/courses': typeof ApiAdminCoursesRouteWithChildren
  '/api/admin/uploads': typeof ApiAdminUploadsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/course/details': typeof ApiCourseDetailsRoute
  '/api/course/progress': typeof ApiCourseProgressRoute
  '/api/cron/blob-sweep': typeof ApiCronBlobSweepRoute
  '/api/lesson/material': typeof ApiLessonMaterialRoute
  '/api/lesson/video': typeof ApiLessonVideoRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/admin/$courseId/editor': typeof AuthedAdminCourseIdEditorRoute
  '/api/admin/courses/$courseId': typeof ApiAdminCoursesCourseIdRouteWithChildren
  '/api/admin/modules/$moduleId': typeof ApiAdminModulesModuleIdRouteWithChildren
  '/api/lesson/ai-test/evaluate': typeof ApiLessonAiTestEvaluateRoute
  '/api/lesson/ai-test/generate': typeof ApiLessonAiTestGenerateRoute
  '/api/lesson/ai-test/results': typeof ApiLessonAiTestResultsRoute
  '/api/lesson/ai-test/save-results': typeof ApiLessonAiTestSaveResultsRoute
  '/modules/$moduleSlug/lessons/$lessonSlug': typeof AuthedModulesModuleSlugLessonsLessonSlugRoute
  '/api/admin/courses/$courseId/board': typeof ApiAdminCoursesCourseIdBoardRoute
  '/api/admin/courses/$courseId/modules': typeof ApiAdminCoursesCourseIdModulesRoute
  '/api/admin/modules/$moduleId/lessons': typeof ApiAdminModulesModuleIdLessonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthedAppRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/admin/courses': typeof ApiAdminCoursesRouteWithChildren
  '/api/admin/uploads': typeof ApiAdminUploadsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/course/details': typeof ApiCourseDetailsRoute
  '/api/course/progress': typeof ApiCourseProgressRoute
  '/api/cron/blob-sweep': typeof ApiCronBlobSweepRoute
  '/api/lesson/material': typeof ApiLessonMaterialRoute
  '/api/lesson/video': typeof ApiLessonVideoRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/$courseId/editor': typeof AuthedAdminCourseIdEditorRoute
  '/api/admin/courses/$courseId': typeof ApiAdminCoursesCourseIdRouteWithChildren
  '/api/admin/modules/$moduleId': typeof ApiAdminModulesModuleIdRouteWithChildren
  '/api/lesson/ai-test/evaluate': typeof ApiLessonAiTestEvaluateRoute
  '/api/lesson/ai-test/generate': typeof ApiLessonAiTestGenerateRoute
  '/api/lesson/ai-test/results': typeof ApiLessonAiTestResultsRoute
  '/api/lesson/ai-test/save-results': typeof ApiLessonAiTestSaveResultsRoute
  '/modules/$moduleSlug/lessons/$lessonSlug': typeof AuthedModulesModuleSlugLessonsLessonSlugRoute
  '/api/admin/courses/$courseId/board': typeof ApiAdminCoursesCourseIdBoardRoute
  '/api/admin/courses/$courseId/modules': typeof ApiAdminCoursesCourseIdModulesRoute
  '/api/admin/modules/$moduleId/lessons': typeof ApiAdminModulesModuleIdLessonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/app': typeof AuthedAppRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/admin/courses': typeof ApiAdminCoursesRouteWithChildren
  '/api/admin/uploads': typeof ApiAdminUploadsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/course/details': typeof ApiCourseDetailsRoute
  '/api/course/progress': typeof ApiCourseProgressRoute
  '/api/cron/blob-sweep': typeof ApiCronBlobSweepRoute
  '/api/lesson/material': typeof ApiLessonMaterialRoute
  '/api/lesson/video': typeof ApiLessonVideoRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/admin/$courseId/editor': typeof AuthedAdminCourseIdEditorRoute
  '/api/admin/courses/$courseId': typeof ApiAdminCoursesCourseIdRouteWithChildren
  '/api/admin/modules/$moduleId': typeof ApiAdminModulesModuleIdRouteWithChildren
  '/api/lesson/ai-test/evaluate': typeof ApiLessonAiTestEvaluateRoute
  '/api/lesson/ai-test/generate': typeof ApiLessonAiTestGenerateRoute
  '/api/lesson/ai-test/results': typeof ApiLessonAiTestResultsRoute
  '/api/lesson/ai-test/save-results': typeof ApiLessonAiTestSaveResultsRoute
  '/_authed/modules/$moduleSlug/lessons/$lessonSlug': typeof AuthedModulesModuleSlugLessonsLessonSlugRoute
  '/api/admin/courses/$courseId/board': typeof ApiAdminCoursesCourseIdBoardRoute
  '/api/admin/courses/$courseId/modules': typeof ApiAdminCoursesCourseIdModulesRoute
  '/api/admin/modules/$moduleId/lessons': typeof ApiAdminModulesModuleIdLessonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth/login'
    | '/api/admin/courses'
    | '/api/admin/uploads'
    | '/api/auth/$'
    | '/api/course/details'
    | '/api/course/progress'
    | '/api/cron/blob-sweep'
    | '/api/lesson/material'
    | '/api/lesson/video'
    | '/admin/'
    | '/admin/$courseId/editor'
    | '/api/admin/courses/$courseId'
    | '/api/admin/modules/$moduleId'
    | '/api/lesson/ai-test/evaluate'
    | '/api/lesson/ai-test/generate'
    | '/api/lesson/ai-test/results'
    | '/api/lesson/ai-test/save-results'
    | '/modules/$moduleSlug/lessons/$lessonSlug'
    | '/api/admin/courses/$courseId/board'
    | '/api/admin/courses/$courseId/modules'
    | '/api/admin/modules/$moduleId/lessons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth/login'
    | '/api/admin/courses'
    | '/api/admin/uploads'
    | '/api/auth/$'
    | '/api/course/details'
    | '/api/course/progress'
    | '/api/cron/blob-sweep'
    | '/api/lesson/material'
    | '/api/lesson/video'
    | '/admin'
    | '/admin/$courseId/editor'
    | '/api/admin/courses/$courseId'
    | '/api/admin/modules/$moduleId'
    | '/api/lesson/ai-test/evaluate'
    | '/api/lesson/ai-test/generate'
    | '/api/lesson/ai-test/results'
    | '/api/lesson/ai-test/save-results'
    | '/modules/$moduleSlug/lessons/$lessonSlug'
    | '/api/admin/courses/$courseId/board'
    | '/api/admin/courses/$courseId/modules'
    | '/api/admin/modules/$moduleId/lessons'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/admin'
    | '/_authed/app'
    | '/auth/login'
    | '/api/admin/courses'
    | '/api/admin/uploads'
    | '/api/auth/$'
    | '/api/course/details'
    | '/api/course/progress'
    | '/api/cron/blob-sweep'
    | '/api/lesson/material'
    | '/api/lesson/video'
    | '/_authed/admin/'
    | '/_authed/admin/$courseId/editor'
    | '/api/admin/courses/$courseId'
    | '/api/admin/modules/$moduleId'
    | '/api/lesson/ai-test/evaluate'
    | '/api/lesson/ai-test/generate'
    | '/api/lesson/ai-test/results'
    | '/api/lesson/ai-test/save-results'
    | '/_authed/modules/$moduleSlug/lessons/$lessonSlug'
    | '/api/admin/courses/$courseId/board'
    | '/api/admin/courses/$courseId/modules'
    | '/api/admin/modules/$moduleId/lessons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAdminCoursesRoute: typeof ApiAdminCoursesRouteWithChildren
  ApiAdminUploadsRoute: typeof ApiAdminUploadsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCourseDetailsRoute: typeof ApiCourseDetailsRoute
  ApiCourseProgressRoute: typeof ApiCourseProgressRoute
  ApiCronBlobSweepRoute: typeof ApiCronBlobSweepRoute
  ApiLessonMaterialRoute: typeof ApiLessonMaterialRoute
  ApiLessonVideoRoute: typeof ApiLessonVideoRoute
  ApiAdminModulesModuleIdRoute: typeof ApiAdminModulesModuleIdRouteWithChildren
  ApiLessonAiTestEvaluateRoute: typeof ApiLessonAiTestEvaluateRoute
  ApiLessonAiTestGenerateRoute: typeof ApiLessonAiTestGenerateRoute
  ApiLessonAiTestResultsRoute: typeof ApiLessonAiTestResultsRoute
  ApiLessonAiTestSaveResultsRoute: typeof ApiLessonAiTestSaveResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/api/lesson/video': {
      id: '/api/lesson/video'
      path: '/api/lesson/video'
      fullPath: '/api/lesson/video'
      preLoaderRoute: typeof ApiLessonVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/material': {
      id: '/api/lesson/material'
      path: '/api/lesson/material'
      fullPath: '/api/lesson/material'
      preLoaderRoute: typeof ApiLessonMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/blob-sweep': {
      id: '/api/cron/blob-sweep'
      path: '/api/cron/blob-sweep'
      fullPath: '/api/cron/blob-sweep'
      preLoaderRoute: typeof ApiCronBlobSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course/progress': {
      id: '/api/course/progress'
      path: '/api/course/progress'
      fullPath: '/api/course/progress'
      preLoaderRoute: typeof ApiCourseProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course/details': {
      id: '/api/course/details'
      path: '/api/course/details'
      fullPath: '/api/course/details'
      preLoaderRoute: typeof ApiCourseDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/uploads': {
      id: '/api/admin/uploads'
      path: '/api/admin/uploads'
      fullPath: '/api/admin/uploads'
      preLoaderRoute: typeof ApiAdminUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/courses': {
      id: '/api/admin/courses'
      path: '/api/admin/courses'
      fullPath: '/api/admin/courses'
      preLoaderRoute: typeof ApiAdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/ai-test/save-results': {
      id: '/api/lesson/ai-test/save-results'
      path: '/api/lesson/ai-test/save-results'
      fullPath: '/api/lesson/ai-test/save-results'
      preLoaderRoute: typeof ApiLessonAiTestSaveResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/ai-test/results': {
      id: '/api/lesson/ai-test/results'
      path: '/api/lesson/ai-test/results'
      fullPath: '/api/lesson/ai-test/results'
      preLoaderRoute: typeof ApiLessonAiTestResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/ai-test/generate': {
      id: '/api/lesson/ai-test/generate'
      path: '/api/lesson/ai-test/generate'
      fullPath: '/api/lesson/ai-test/generate'
      preLoaderRoute: typeof ApiLessonAiTestGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/ai-test/evaluate': {
      id: '/api/lesson/ai-test/evaluate'
      path: '/api/lesson/ai-test/evaluate'
      fullPath: '/api/lesson/ai-test/evaluate'
      preLoaderRoute: typeof ApiLessonAiTestEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/modules/$moduleId': {
      id: '/api/admin/modules/$moduleId'
      path: '/api/admin/modules/$moduleId'
      fullPath: '/api/admin/modules/$moduleId'
      preLoaderRoute: typeof ApiAdminModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/courses/$courseId': {
      id: '/api/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/api/admin/courses/$courseId'
      preLoaderRoute: typeof ApiAdminCoursesCourseIdRouteImport
      parentRoute: typeof ApiAdminCoursesRoute
    }
    '/_authed/admin/$courseId/editor': {
      id: '/_authed/admin/$courseId/editor'
      path: '/$courseId/editor'
      fullPath: '/admin/$courseId/editor'
      preLoaderRoute: typeof AuthedAdminCourseIdEditorRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/api/admin/modules/$moduleId/lessons': {
      id: '/api/admin/modules/$moduleId/lessons'
      path: '/lessons'
      fullPath: '/api/admin/modules/$moduleId/lessons'
      preLoaderRoute: typeof ApiAdminModulesModuleIdLessonsRouteImport
      parentRoute: typeof ApiAdminModulesModuleIdRoute
    }
    '/api/admin/courses/$courseId/modules': {
      id: '/api/admin/courses/$courseId/modules'
      path: '/modules'
      fullPath: '/api/admin/courses/$courseId/modules'
      preLoaderRoute: typeof ApiAdminCoursesCourseIdModulesRouteImport
      parentRoute: typeof ApiAdminCoursesCourseIdRoute
    }
    '/api/admin/courses/$courseId/board': {
      id: '/api/admin/courses/$courseId/board'
      path: '/board'
      fullPath: '/api/admin/courses/$courseId/board'
      preLoaderRoute: typeof ApiAdminCoursesCourseIdBoardRouteImport
      parentRoute: typeof ApiAdminCoursesCourseIdRoute
    }
    '/_authed/modules/$moduleSlug/lessons/$lessonSlug': {
      id: '/_authed/modules/$moduleSlug/lessons/$lessonSlug'
      path: '/modules/$moduleSlug/lessons/$lessonSlug'
      fullPath: '/modules/$moduleSlug/lessons/$lessonSlug'
      preLoaderRoute: typeof AuthedModulesModuleSlugLessonsLessonSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminCourseIdEditorRoute: typeof AuthedAdminCourseIdEditorRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminCourseIdEditorRoute: AuthedAdminCourseIdEditorRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRoute
  AuthedModulesModuleSlugLessonsLessonSlugRoute: typeof AuthedModulesModuleSlugLessonsLessonSlugRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedAppRoute: AuthedAppRoute,
  AuthedModulesModuleSlugLessonsLessonSlugRoute:
    AuthedModulesModuleSlugLessonsLessonSlugRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiAdminCoursesCourseIdRouteChildren {
  ApiAdminCoursesCourseIdBoardRoute: typeof ApiAdminCoursesCourseIdBoardRoute
  ApiAdminCoursesCourseIdModulesRoute: typeof ApiAdminCoursesCourseIdModulesRoute
}

const ApiAdminCoursesCourseIdRouteChildren: ApiAdminCoursesCourseIdRouteChildren =
  {
    ApiAdminCoursesCourseIdBoardRoute: ApiAdminCoursesCourseIdBoardRoute,
    ApiAdminCoursesCourseIdModulesRoute: ApiAdminCoursesCourseIdModulesRoute,
  }

const ApiAdminCoursesCourseIdRouteWithChildren =
  ApiAdminCoursesCourseIdRoute._addFileChildren(
    ApiAdminCoursesCourseIdRouteChildren,
  )

interface ApiAdminCoursesRouteChildren {
  ApiAdminCoursesCourseIdRoute: typeof ApiAdminCoursesCourseIdRouteWithChildren
}

const ApiAdminCoursesRouteChildren: ApiAdminCoursesRouteChildren = {
  ApiAdminCoursesCourseIdRoute: ApiAdminCoursesCourseIdRouteWithChildren,
}

const ApiAdminCoursesRouteWithChildren = ApiAdminCoursesRoute._addFileChildren(
  ApiAdminCoursesRouteChildren,
)

interface ApiAdminModulesModuleIdRouteChildren {
  ApiAdminModulesModuleIdLessonsRoute: typeof ApiAdminModulesModuleIdLessonsRoute
}

const ApiAdminModulesModuleIdRouteChildren: ApiAdminModulesModuleIdRouteChildren =
  {
    ApiAdminModulesModuleIdLessonsRoute: ApiAdminModulesModuleIdLessonsRoute,
  }

const ApiAdminModulesModuleIdRouteWithChildren =
  ApiAdminModulesModuleIdRoute._addFileChildren(
    ApiAdminModulesModuleIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  ApiAdminCoursesRoute: ApiAdminCoursesRouteWithChildren,
  ApiAdminUploadsRoute: ApiAdminUploadsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCourseDetailsRoute: ApiCourseDetailsRoute,
  ApiCourseProgressRoute: ApiCourseProgressRoute,
  ApiCronBlobSweepRoute: ApiCronBlobSweepRoute,
  ApiLessonMaterialRoute: ApiLessonMaterialRoute,
  ApiLessonVideoRoute: ApiLessonVideoRoute,
  ApiAdminModulesModuleIdRoute: ApiAdminModulesModuleIdRouteWithChildren,
  ApiLessonAiTestEvaluateRoute: ApiLessonAiTestEvaluateRoute,
  ApiLessonAiTestGenerateRoute: ApiLessonAiTestGenerateRoute,
  ApiLessonAiTestResultsRoute: ApiLessonAiTestResultsRoute,
  ApiLessonAiTestSaveResultsRoute: ApiLessonAiTestSaveResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
